# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Selleo < Formula
  desc "Selleo's CLI to make better DX"
  homepage "https://github.com/selleo/cli"
  version "0.10.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Selleo/cli/releases/download/v0.10.2/cli_0.10.2_darwin_amd64.tar.gz"
      sha256 "0eb6ea02a35b599df7ce5ce69bc664e88b03df3f29a344a5683ca141da7eb37b"

      def install
        bin.install "selleo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Selleo/cli/releases/download/v0.10.2/cli_0.10.2_darwin_arm64.tar.gz"
      sha256 "9b188f95cc75b858f4470700b87b5ba34b2e9216f92895a40ecd9a1dc5348910"

      def install
        bin.install "selleo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Selleo/cli/releases/download/v0.10.2/cli_0.10.2_linux_amd64.tar.gz"
      sha256 "5e7919e1d5e2a50a268d54fd3b2ade702d401b88ffb17c5dbf2f668b51b31bab"

      def install
        bin.install "selleo"
      end
    end
  end
end
