# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Selleo < Formula
  desc "Selleo's CLI for better developer experience."
  homepage "https://github.com/selleo/cli"
  version "0.26.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Selleo/cli/releases/download/v0.26.0/cli_0.26.0_darwin_arm64.tar.gz"
      sha256 "d759f333223c657c445f3925b2e35fabc7876ebad2c4812822e9218b388cf788"

      def install
        bin.install "selleo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Selleo/cli/releases/download/v0.26.0/cli_0.26.0_darwin_amd64.tar.gz"
      sha256 "31bafec4b56fa5ac900f8b05ff0dffda2191b07232ab634a79ecaf4ce8a3e842"

      def install
        bin.install "selleo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Selleo/cli/releases/download/v0.26.0/cli_0.26.0_linux_amd64.tar.gz"
      sha256 "fde962bdfb7d7e442e4c0ba3a2bb0d7e3f6ca7834d7ac406957cd9d8b17d49fe"

      def install
        bin.install "selleo"
      end
    end
  end
end
