# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Selleo < Formula
  desc "Selleo's CLI for better developer experience."
  homepage "https://github.com/selleo/cli"
  version "0.12.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Selleo/cli/releases/download/v0.12.0/cli_0.12.0_darwin_amd64.tar.gz"
      sha256 "05b1493d2dc598481d57ae44aa94f436ec045ef9b0c173b6dad04f30d45aecdc"

      def install
        bin.install "selleo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Selleo/cli/releases/download/v0.12.0/cli_0.12.0_darwin_arm64.tar.gz"
      sha256 "d07eba0d1d3c5e156ec93c673a635333887453bfe2431128503674f4e8eb1d95"

      def install
        bin.install "selleo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Selleo/cli/releases/download/v0.12.0/cli_0.12.0_linux_amd64.tar.gz"
      sha256 "2e40b37b06832324bf82406c8a14a29af785edcbefde1a9d43fbbe94ccd4f480"

      def install
        bin.install "selleo"
      end
    end
  end
end
