# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Selleo < Formula
  desc "Selleo's CLI for better developer experience."
  homepage "https://github.com/selleo/cli"
  version "0.13.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Selleo/cli/releases/download/v0.13.0/cli_0.13.0_darwin_arm64.tar.gz"
      sha256 "3b49a49621cc8401dbdc77f88fafc3c2b537ddf84b8e55a65166f69d944bc99d"

      def install
        bin.install "selleo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Selleo/cli/releases/download/v0.13.0/cli_0.13.0_darwin_amd64.tar.gz"
      sha256 "952b08d5366eae9ecca7a5831d5394c99662914f60f253bfc756487400e830b0"

      def install
        bin.install "selleo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Selleo/cli/releases/download/v0.13.0/cli_0.13.0_linux_amd64.tar.gz"
      sha256 "c41e89b577fde9323faa17733442e71ac0102e4c74b771f01af08b8e9ad21544"

      def install
        bin.install "selleo"
      end
    end
  end
end
